### ISSUE TITLE
Clarification on Scores within the Dataset

### ISSUE THREAD

**Issue by Ryze-jo** [graspnet/graspnet-baseline#100]
Hello,@Fang-Haoshu @chenxi-wang @colin-zgf 

I am currently exploring the graspnet1billion 6d grasp dataset and have encountered some confusion regarding the interpretation of the scores within the grasp labels. 

Could you please clarify whether these scores represent the friction coefficient or if they are indicative of 1- friction coefficient?

Understanding this distinction is crucial for the accurate application and interpretation of the data. I would greatly appreciate any detailed explanation you could provide on this matter.Looking forward to your response.Thank you!

**Comment by chenxi-wang** [comment]
In the labels, "score" stands for the friction coefficient. A lower "score" means higher grasp quality.
