### ISSUE TITLE
What's the usage of the function "process_grasp_labels" in the "label_generation.py" file ?

### ISSUE THREAD

**Issue by Cwyxx** [graspnet/graspnet-baseline#102]

**Comment by Cwyxx** [comment]
I am baffled about it, can you explain it specifically? Thank you very much! @chenxi-wang @Fang-Haoshu  @colin-zgf

**Comment by chenxi-wang** [comment]
There is no one-to-one match between the predictions and pre-generated grasp labels. So we use this function to sample and assign the nearest label to each prediction by computing the point distances and rotation errors.

**Comment by Cwyxx** [comment]
Thank you very much!
