### ISSUE TITLE
Camera positions with respect to robot reference frames

### ISSUE THREAD

**Issue by davidea97** [graspnet/graspnet-baseline#116]
Thanks for the great work! Is there any file reporting the camera extrinsic parameters which describe the relative position between the camera and a robot reference frame (e.g., the hand-eye transformation)?

**Comment by chenxi-wang** [comment]
Hi, the input point clouds and output grasps are in camera frame, so extrinsic parameters are not required during inference. In real robot experiments, you can transform the grasps according to your calibration result.
