### ISSUE TITLE
output the model to .pt file to implement in c++

### ISSUE THREAD

**Issue by Twilight89** [graspnet/graspnet-baseline#13]
Hi~ When I  output the model to .pt file() [in demo.py]
`        example = end_points['point_clouds']
        traced_script_module = torch.jit.trace(net, example)

        traced_script_module.save("model-graspnet.pt")`
[I have changed the input and output of the net to tensors to trace]
But  I get error like this:
Traceback (most recent call last):
  File "demo.py", line 162, in <module>
    demo(data_dir)
  File "demo.py", line 147, in demo
    traced_script_module.save("model-graspnet.pt")
  File "/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/jit/__init__.py", line 1987, in save
    return self._c.save(*args, **kwargs)
RuntimeError: 
Could not export Python function call 'FurthestPointSampling'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
/home/twilight/project/graspnet-baseline/pointnet2/pointnet2_modules.py(235): forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/twilight/project/graspnet-baseline/models/backbone.py(105): forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/twilight/project/graspnet-baseline/models/graspnet.py(33): forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/twilight/project/graspnet-baseline/models/graspnet.py(74): forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/jit/__init__.py(1109): trace_module
/home/twilight/anaconda3/envs/graspnet/lib/python3.7/site-packages/torch/jit/__init__.py(955): trace
demo.py(145): demo
demo.py(162): <module>
I don't know why, can you help me?

**Comment by chenxi-wang** [comment]
Hi, looks like something going wrong with pointnet++ operator, which is not originally implemented in pytorch. I'm not clear about the problem because I never tried torch.jit. Did you try to follow the tips in logs? Or you can search pytorch forum for help.
