### ISSUE TITLE
About the "end_points['fp2_inds'] " in backbone.py

### ISSUE THREAD

**Issue by GalenOOO** [graspnet/graspnet-baseline#21]
In line 129 of models/backbone.py      
129:     end_points['fp2_inds'] = end_points['sa1_inds'][:,0:num_seed] # indices among the entire input point clouds

why just 0:num_seed ? It seems the results are not fp2_inds.

**Comment by laynewong** [comment]
I have the same doubts as you. I think it might be better to change to the following way.
`end_points['fp2_inds'] = torch.gather(end_points['sa1_inds'], dim=1, index=end_points['sa2_inds'].long())`

**Comment by 19915370507** [comment]
请问，end_points['fp2_inds'] 这里指的是什么

**Comment by kliocon** [comment]
@GalenOOO @Fang-Haoshu @laynewong @chenxi-wang  Have you solved this problem? I also think that the points of the index and the upsampling do not match
