### ISSUE TITLE
About load_grasp_labels and objectness_label in graspnet_dataset.py

### ISSUE THREAD

**Issue by rhett-chen** [graspnet/graspnet-baseline#26]
Hi，thanks for your great work！I have two questions about your code：

1. https://github.com/graspnet/graspnet-baseline/blob/df67956a1fecadf5b47ffe141103edfb8deec543/dataset/graspnet_dataset.py#L199
You set objectness_label > 1, which will lose the label of object id=0 in segmentation mask.  I want to know why it's not objectness_label > 0?
2. https://github.com/graspnet/graspnet-baseline/blob/df67956a1fecadf5b47ffe141103edfb8deec543/dataset/graspnet_dataset.py#L255
I wonder why you just skip the object id=18 in load_grasp_labels function？
Hope to hear your response soon, thanks!

**Comment by chenxi-wang** [comment]
Hi, the original objectness label contains object ids from 0 to n, where n is the number of objects and object 0 indicates background. It share the same format with YCB-Video dataset. Hence, objectness>1 and objectness>0 bring the same results.
The grasp label of object 18 is too large, which leads to OOM. So I skipped this object in training.
