### ISSUE TITLE
Grasps on table

### ISSUE THREAD

**Issue by FrancescoRosa3** [graspnet/graspnet-baseline#27]
Hi everyone.
I was trying to run the detector on new point clouds taken from Gazebo, through a plugin that simulates the Realsense-435 camera,
After the inference process, I obtained grasps that are on the "floor".
![Screenshot from 2021-08-11 17-53-40](https://user-images.githubusercontent.com/63720233/129062449-e09c68ee-f90f-4d61-9bd7-0fddc7649b86.png)
By reading issue #18 you talked about a possible wrong objectness mask due to incorrect coordinate frames.
I would like to know what did you mean in detail, and how could I resolve this problem? 
I know that I could filter out the background point, but from the demo you have provided, it seems to me that, it is not performed any background subtraction, is it?
Thanks for your kind.

**Comment by chenxi-wang** [comment]
Not sure if the translation of your cloud is different with our setting. Our method to transform points from pixel coordinate frame to camera coordinate frame is define [here](https://github.com/graspnet/graspnet-baseline/blob/main/utils/data_utils.py#L18), and you can have a check.
