### ISSUE TITLE
Problems with the generated rotation matrix

### ISSUE THREAD

**Issue by JingKangSun** [graspnet/graspnet-baseline#28]
Hi @chenxi-wang,

I was trying to transplanted this algorithm to the real robotic arm.

I found that the rotation matrixs generated by the pretrained model have difference with the real camera frame.Specifically,I need to multiply a matrix to the left of the  rotation matrixs generated by the pretrained model,then I can get the correct matrixs under the camera frame.And the matrix T which I need to multiply left is:[0,0,1;1,0,0;0,1,0]

Blow is a instance of my question,the frame A is the camera frame,the frame B is the target frame generated by the pretrained model,the frame C is multiply T to the left of the frame B,and this is the frame corrspond to real camera frame:

![{N%GVN73_PS%5}U3I27P6CT](https://user-images.githubusercontent.com/89125332/130185288-e6293310-d802-4b2a-bfb5-276e146ba77f.png)

Can you tell me why I need to multiply a matrix to the left of the  rotation matrixs generated by the pretrained model?Thanks!

Regards,
JingKang

**Comment by chenxi-wang** [comment]
Could you provide specific examples for clearer explanations? I cannot figure out your meaning.

**Comment by shineYuSong** [comment]
> Hi @chenxi-wang,
> 
> I was trying to transplanted this algorithm to the real robotic arm.
> 
> I found that the rotation matrixs generated by the pretrained model have difference with the real camera frame.Specifically,I need to multiply a matrix to the left of the rotation matrixs generated by the pretrained model,then I can get the correct matrixs under the camera frame.And the matrix T which I need to multiply left is:[0,0,1;1,0,0;0,1,0]
> 
> Blow is a instance of my question,the frame A is the camera frame,the frame B is the target frame generated by the pretrained model,the frame C is multiply T to the left of the frame B,and this is the frame corrspond to real camera frame:
> 
> ![{N%GVN73_PS%5}U3I27P6CT](https://user-images.githubusercontent.com/89125332/130185288-e6293310-d802-4b2a-bfb5-276e146ba77f.png)
> 
> Can you tell me why I need to multiply a matrix to the left of the rotation matrixs generated by the pretrained model?Thanks!
> 
> Regards, JingKang

I am trying to apply this project to my real robotic arm too, have you finished? I was confused about the datainput that i only provide the rgb and depth information, the code in this project is locked with so much detial information, can you share your solution？
