### ISSUE TITLE
How to annotate own dataset?

### ISSUE THREAD

**Issue by saprrow** [graspnet/graspnet-baseline#33]
Could you provide more detailed docs or tools for annotating grasp poses?
Thanks!

**Comment by Fang-Haoshu** [comment]
Hi, if you are interested in the object grasp pose annotation, you can fill out this form and I will invite you later on: https://forms.gle/7o4f18UHsw55nQ256

**Comment by saprrow** [comment]
@Fang-Haoshu Thanks a lot! I've filled out the form.

**Comment by willieChen58** [comment]
> Hi, if you are interested in the object grasp pose annotation, you can fill out this form and I will invite you later on: https://forms.gle/7o4f18UHsw55nQ256

@Fang-Haoshu Hi, I've filled out the form, could you provide tool for annotating grasp poses?

**Comment by saprrow** [comment]
Hi, Haosu
      I've applied through the form you shared, But I haven't got the annotation toolbox.
      I will appreciate it if you could share your toolbox with me.
      Thanks again for your fantastic work.

Best regards,
Jarvi
________________________________
发件人: willieChen58 ***@***.***>
发送时间: 2023年11月10日 13:19
收件人: graspnet/graspnet-baseline ***@***.***>
抄送: sparrow ***@***.***>; Author ***@***.***>
主题: Re: [graspnet/graspnet-baseline] How to annotate own dataset? (Issue #33)


Hi, if you are interested in the object grasp pose annotation, you can fill out this form and I will invite you later on: https://forms.gle/7o4f18UHsw55nQ256

@Fang-Haoshu<https://github.com/Fang-Haoshu> Hi, I've filled out the form, could you provide tool for annotating grasp poses?

**Comment by Fang-Haoshu** [comment]
@saprrow @willieChen58 invited

**Comment by sneakerheyujie** [comment]
I am interested in grasp pose annotation. Can you also provide me with the  annotation toolbox

**Comment by xinchaosong** [comment]
@Fang-Haoshu I'm also interested in the annotation tool and have filled out the form. Can you please invite me? Thank you very much!

**Comment by Fang-Haoshu** [comment]
invited

**Comment by yhl41001** [comment]
@Fang-Haoshu Hi, I've filled out the form, could you provide tool for annotating grasp poses?

**Comment by gachiemchiep** [comment]
@Fang-Haoshu Hello. Sorry to bother you. I've filled out the form, would you mind invite me to the  grasp poses annotation tool? Thank you very much

**Comment by huiwenzhang** [comment]
Hi,  does the annotation tool use kind of icp or linemod to get the ground-truth object pose?

**Comment by sms95** [comment]
@Fang-Haoshu  
Hi, I've filled out the form weeks ago, would you mind invite me? Thank you very much!

**Comment by Akiol1366** [comment]
@Fang-Haoshu 
Hi, I've filled out the form weeks ago, would you mind invite me? Thank you very much!

**Comment by Fang-Haoshu** [comment]
Invited

**Comment by zhangzilongc** [comment]
@Fang-Haoshu 
Hi, I've filled out the form weeks ago, would you mind invite me? Thank you very much!

**Comment by Carolinadeveloper** [comment]
Thanks for your great job! @Fang-Haoshu 
 I've filled out the form weeks ago,could you invite me? Thanks a lot!

**Comment by Fang-Haoshu** [comment]
invited @zhangzilongc

**Comment by Fang-Haoshu** [comment]
I couldn't find your application from weeks ago, what's your email? @Carolinadeveloper

**Comment by Carolinadeveloper** [comment]
> I couldn't find your application from weeks ago, what's your email? [@Carolinadeveloper](https://github.com/Carolinadeveloper)
The email I filled in the form is carolinadeveloper@163.com

**Comment by gachiemchiep** [comment]
@Fang-Haoshu 
Hello. Would you mind send me the invitation again?

**Comment by Carolinadeveloper** [comment]
sorry for bothering you again, I I've filled out the form, my email is above mentioned. Could u invite me? Thanks a lot! @Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
@gachiemchiep @Carolinadeveloper Invited

**Comment by Hriver-J** [comment]
@Fang-Haoshu 
Hi, sorry for bother you, I've filled out the form, could you please invite me for the tool? Thanks for your patience!

**Comment by Hriver-J** [comment]
@Fang-Haoshu 
Hi, sorry for bothering you, I've filled out the form, could you please invite me for the tool? Thanks for your patience!

**Comment by tangshp-hub** [comment]
"Thank you very much for your open-source code. I would like to learn how to annotate my own dataset. Could you please share some guidance? My email is 791276448@qq.com."

**Comment by Fang-Haoshu** [comment]
invited

**Comment by edwin191** [comment]
@Fang-Haoshu Hi~I have filled the form, could you invite me ? many thanks

**Comment by sankar-90210** [comment]
@Fang-Haoshu  Hello thanks for the good work! I have filled the form as I am interested in the annotation tool for grasp poses. Could you please invite me? Thanks in advance!

**Comment by sankar-90210** [comment]
> [@Fang-Haoshu](https://github.com/Fang-Haoshu) Hello thanks for the good work! I have filled the form as I am interested in the annotation tool for grasp poses. Could you please invite me? Thanks in advance!

Hello sorry for bothering! Can you please invite me? Thank you!
