### ISSUE TITLE
Grasps not on object + what is grasp height and depth?

### ISSUE THREAD

**Issue by holst456** [graspnet/graspnet-baseline#34]
@Fang-Haoshu @chenxi-wang
Thanks for this publication as well as the open source code.

I have a question reagarding the resulting grasps. Using the pretrained weights and the demo code, the network will sometimes not return any grasps on the object:
![image](https://user-images.githubusercontent.com/61350363/139227661-0e1e82bb-edea-4744-bf3b-174c75714838.png)
Do you have any idea how to make it work in this scenario?

Additionally, I do not understand how to use the grasp depth and height. I looked at [this](https://github.com/graspnet/graspnet-baseline/issues/7) issue, but still do not get what this information represents.

Using a parallel gripper, shouldn't the translation and rotation be enough to determine where to grasp the object? 
I have implemented your code on a Universal Robots manipulator mounted with Realsense d435 and OnRobot parallel gripper, and when sending the TCP to the grasp translation and rotation, it always seem to be a few cm short of gripping the object correct. Could this be related to not using the depth and height information?

Best regards,
Emil Holst

**Comment by chenxi-wang** [comment]
Hi, you can refer to [this issue](https://github.com/graspnet/graspnet-baseline/issues/18#issuecomment-873758326) for the first problem.
For the second problem, the translation is the location of gripper center in camera coordinates, where the "center" is the origin of gripper coordinates (defined [here](https://github.com/graspnet/graspnet-baseline/issues/7#issuecomment-760593025)). You can refer to [this issue](https://github.com/graspnet/graspnet-baseline/issues/23#issuecomment-892514277).

**Comment by holst456** [comment]
Thank you for your answer. I already have an object mask for each object, so I will try to use that instead. I have translated the grasp point forward in the gripper frame (the rotation and translation) by the depth-parameter and that seems to work pretty good. I am still unsure about how to understand the height parameter in relation to gripper frame. What does it represent the height of?

**Comment by chenxi-wang** [comment]
The "height" is the thickness of a gripper, which is used in collision detection. You can modify height according to your gripper.

**Comment by holst456** [comment]
> The "height" is the thickness of a gripper, which is used in collision detection. You can modify height according to your gripper.

Okay thanks
