### ISSUE TITLE
关于grasp score的问题

### ISSUE THREAD

**Issue by xiaozheng-liu** [graspnet/graspnet-baseline#40]
作者您好，首先感谢您团队能开源这么棒的工作。我在阅读您论文的过程中，发现抓取分数的计算准则一直在变化：
（1）在CVPR2020 GraspNet-1Billion中，您定义的抓取分数是：s = 1.1-u
（2）在开源的代码中，采取的抓取分数是：s = ln(Umax / u)
（3）在最新的ICCV2021中，采取的抓取分数是：s = lu(Umax / u)  /  ln(Umax/Umin)，分数被归一化到[0, 1]
所以，请问为什么要进行这种变化？（3）与（2）相比，归一化到[0, 1]有助于模型训练吗？期待您的回复，感谢。

**Comment by chenxi-wang** [comment]
原论文中 grasp score 随摩擦系数线性变化，但是抓取质量跟摩擦系数阈值 μ 并不是严格线性相关的，我们更关注质量较高的抓取；另一方面，在数据集中抓取姿态随 μ 的分布不是均匀分布，μ=0.1 的样本数远少于 μ=1.0 的，不利于训练。因此 baseline 中将 score 从（1）中随 μ 线性变化改为（2）中的对数变化，以提高头部样本的区分度。

在 gsnet 中的改动没有特殊含义，GOM 中同时预测了 width 和 score，统一做归一化处理，效果差别不大。
