### ISSUE TITLE
Is this result right?

### ISSUE THREAD

**Issue by kaku2000** [graspnet/graspnet-baseline#43]
My environment is :

OS：Ubuntu 22.04.1 LTS
CUDA：11.7     sm_86
Pytorch：1.8.0

Since I couldn't successfully install pytorch_knn_cuda repo, I installed https://github.com/unlimblue/KNN_CUDA this one instead. And simply replaced "knn" function by the "KNN". 

As a result, when running demo.py with the pretrained checkpoint, no matter using "rs" or "kn",  I get this prediction:

![Screenshot from 2022-09-19 01-00-21](https://user-images.githubusercontent.com/74921867/190916621-c9531608-c90f-40bd-96ed-7f255eda1212.png)

Is this right? Or should I figure out how to install the old pytorch_knn_cuda ?

Thanks.

**Comment by chenxi-wang** [comment]
Hi, the result is incorrect. The knn operator should be installed using the code in ``knn`` folder (in this repo) instead of pytorch_knn_cuda repo.

**Comment by kaku2000** [comment]
> Hi, the result is incorrect. The knn operator should be installed using the code in `knn` folder (in this repo) instead of pytorch_knn_cuda repo.

Oh, it is right, after turning the pointcloud 180 degree LOLLL
