### ISSUE TITLE
Some instances of ground-truth pose have error

### ISSUE THREAD

**Issue by 63445538** [graspnet/graspnet-baseline#45]
The red marker in the picture shows pose error from image 128 with scene 161.
![2022_10_26_0h3_Kleki](https://user-images.githubusercontent.com/16507095/197919033-f0352ab6-f806-4520-ae76-8607bec5c3d9.png)

Best regards,
Rui Cao

**Comment by 63445538** [comment]
Kinect sensor's result

**Comment by Fang-Haoshu** [comment]
Hi, thanks for reporting the issue. It is possible that some minor annotation errors might still exist, though I have checked the labels manually. Usually, they don't affect the overall evaluation results on the whole test set.
