### ISSUE TITLE
what is the workspace mask? doc/example_data/workspace_mask.png

### ISSUE THREAD

**Issue by xiaofeiso** [graspnet/graspnet-baseline#46]
what is the workspace mask? when  i see doc/example_data/workspace_mask.png , it is a white picture. ICan it be used in any scen?

**Comment by Fang-Haoshu** [comment]
Hi， it is a mask that you can constrain the workspace in the white space. For example, if you want to filter the grasp poses on the table edge, you can set the workspace mask to be on the table without including the table edge.
