### ISSUE TITLE
I am trying to apply this project to my real robotic arm， I was confused about the data input that i only provide the rgb and depth information, while in the baseline the code in this project is locked with so much detial information, so must i supply so much informaiton ?

### ISSUE THREAD

**Issue by shineYuSong** [graspnet/graspnet-baseline#48]

**Comment by Fang-Haoshu** [comment]
If you mean the camera intrinsic matrix, I think it is essential

**Comment by shineYuSong** [comment]
> If you mean the camera intrinsic matrix, I think it is essential

and except for the camera detail, I was confused about the "meta" and "scene ID", if i apply it in my scene, what should i send to these two items? and the seg results is based on rgb data? thank a lot

**Comment by Fang-Haoshu** [comment]
meta only provides camera intrinsic
