### ISSUE TITLE
is there a demo for us to show how to choose the best grasp pose

### ISSUE THREAD

**Issue by dbdxnuliba** [graspnet/graspnet-baseline#52]
By run CUDA_VISIBLE_DEVICES=0 python demo.py --checkpoint_path logs/log_kn/checkpoint-rs.tar
wen an get a lot of grasp poses ,but how can we choose the most appropriate pose from them, is there a demo for us to show how to choose the best grasp pose
![image](https://user-images.githubusercontent.com/13350158/229346315-15b1c5d8-239e-4c0e-8f60-20ac176195c6.png)

**Comment by chenxi-wang** [comment]
That depends on what kind of grasp you want. The output grasps are stored in GraspGroup format (See [this](https://github.com/graspnet/graspnetAPI/blob/master/graspnetAPI/grasp.py#L205) for detail). You can select grasps by adding a limitation mask on gg.scores, gg.translations or gg.rotation_matrices.
