### ISSUE TITLE
About knn in lablel_generation

### ISSUE THREAD

**Issue by stunback** [graspnet/graspnet-baseline#53]
Hello, thanks for your excellent works.
And I have a problem in label_generation.py, line 60 that:
```
view_inds = knn(grasp_views_trans_, grasp_views_, k=1).squeeze() - 1
```
why the knn result indices need to -1 ?

Hope for your reply, thanks a lot.

**Comment by chenxi-wang** [comment]
If I remember correctly, the indices returned from this knn implementation start from 1 instead of 0. So the results need to -1.
