### ISSUE TITLE
Why are all the object_ids in the demo output -1

### ISSUE THREAD

**Issue by cx3307** [graspnet/graspnet-baseline#56]
![image](https://user-images.githubusercontent.com/132656890/236418133-ac271970-c394-4fb9-a3d8-d8cf9ea2d82d.png)
I need the grasp poses of a specific object outputted by GraspNet, but all object_ids outputted by the demo are -1. How can I change this?

**Comment by chenxi-wang** [comment]
The model does not predict object categories, so you need to detect the object first.
You can also modify the network output layer from objectness (0 or 1) to object class ids and train the network from scratch.
