### ISSUE TITLE
How come the output of this model is stochastic? 

### ISSUE THREAD

**Issue by cx3307** [graspnet/graspnet-baseline#57]
How come the output of this model is stochastic? When the same image is input twice, the results obtained are different.
This is my input rgb image:
![color4](https://github.com/graspnet/graspnet-baseline/assets/132656890/e63fb3a3-8ce3-49f5-95be-d8965faa8bd3)
This is the first output:
![image](https://github.com/graspnet/graspnet-baseline/assets/132656890/5fa1b889-3041-4b4a-9ba5-7da7e18be1c2)
This is the second output:
![image](https://github.com/graspnet/graspnet-baseline/assets/132656890/da063431-b2f4-4634-ac18-eb102199d100)

**Comment by chenxi-wang** [comment]
Did you sample the points randomly when creating the point cloud?

**Comment by Fang-Haoshu** [comment]
In the above images, the RGBD images are not the same for the inputs.
