### ISSUE TITLE
How did you avoid the collison?

### ISSUE THREAD

**Issue by ZIXINLinsztu** [graspnet/graspnet-baseline#58]
After I input the RGB and Depth image into the demo.py, I got the prediction data. Then I transform the coordinate so that my robot can move to the target pose, but it would collide the object,. So I wonder how did you avoid the collision between gripper and object in your experiment?

**Comment by Fang-Haoshu** [comment]
Hi, we first move the gripper to a pose that is 10cm backward along the approaching direction of the predicted grasp pose, and then make the gripper moves to the predicted grasp pose along the approaching direction.

**Comment by ZIXINLinsztu** [comment]
> Hi, we first move the gripper to a pose that is 10cm backward along the approaching direction of the predicted grasp pose, and then make the gripper moves to the predicted grasp pose along the approaching direction.

It's helpful for me, thanks!

**Comment by WentangChen** [comment]
> After I input the RGB and Depth image into the demo.py, I got the prediction data. Then I transform the coordinate so that my robot can move to the target pose, but it would collide the object,. So I wonder how did you avoid the collision between gripper and object in your experiment?

hi there, I also input the RGB and Depth image into the demo.py, but i cannot get the prediction data. I wonder if you could offer your code for me to learn about it? Thanks.
