### ISSUE TITLE
Are there any other indicators of how accurate an object is to grasp? I would like to know how accurate the baseline is on common objects

### ISSUE THREAD

**Issue by gzchenjiajun** [graspnet/graspnet-baseline#6]
Are there any other indicators of how accurate an object is to grasp? I would like to know how accurate the baseline is on common objects
![image](https://user-images.githubusercontent.com/13104274/104306281-b9309400-5508-11eb-9541-b4e23e305bd5.png)

**Comment by chenxi-wang** [comment]
Hi, this baseline model is for grasp detection in cluttered scenes, and not designed for a specified object. You can use an object mask to see the result on a single object.

**Comment by gzchenjiajun** [comment]
> Hi, this baseline model is for grasp detection in cluttered scenes, and not designed for a specified object. You can use an object mask to see the result on a single object.

OK, thank you.
I used it before
NVLABS / 6DOF - Graspnet Repo, but their data set is not scalable enough (we want to build our own data set), so we will start to prepare to use your work.
Thank you very much!

**Comment by gzchenjiajun** [comment]
> > Hi, this baseline model is for grasp detection in cluttered scenes, and not designed for a specified object. You can use an object mask to see the result on a single object.
> 
> OK, thank you.
> I used it before
> NVLABS / 6DOF - Graspnet Repo, but their data set is not scalable enough (we want to build our own data set), so we will start to prepare to use your work.
> Thank you very much!

For example, in meta data, I download a dataset and look at meta data, but I don't know how to construct poses, like in meta.
By the way, is there any recommended software for building these data sets? (2D detection tasks like rectLabel are usually performed with software like rectLabel)
thank you

**Comment by gzchenjiajun** [comment]
> > > Hi, this baseline model is for grasp detection in cluttered scenes, and not designed for a specified object. You can use an object mask to see the result on a single object.
> > 
> > 
> > OK, thank you.
> > I used it before
> > NVLABS / 6DOF - Graspnet Repo, but their data set is not scalable enough (we want to build our own data set), so we will start to prepare to use your work.
> > Thank you very much!
> 
> For example, in meta data, I download a dataset and look at meta data, but I don't know how to construct poses, like in meta.
> By the way, is there any recommended software for building these data sets? (2D detection tasks like rectLabel are usually performed with software like rectLabel)
> thank you

I did a little bit of work, I had a little bit of understanding, that it poses maybe point clouds of concrete objects, right? But I see shape is 3*4*9/3*4*10/...
I'm not sure how to construct the data
thank you

**Comment by Fang-Haoshu** [comment]
You should refer to our paper.
These are common concepts in 3D geometry like object pose. You should get these knowledge on internet beforehand.
Thanks

**Comment by gzchenjiajun** [comment]
> concepts

ok
