### ISSUE TITLE
Questions about "score"

### ISSUE THREAD

**Issue by ZIXINLinsztu** [graspnet/graspnet-baseline#60]
Hello, I found that the score of raw labels and 6d labels are different in graspnet API doucument, the lower the score of raw label is the better, while the higher the score of 6D labels is the better. I would like to ask which kind of score output in demo.py file belongs to. And what does the color of the gripper represent in the visualization?

**Comment by Fang-Haoshu** [comment]
Hi， in the demo.py file, the higher score is better. And if the gripper color is more "red", it means the score is higher, thus the grasp pose is better. Bluer color denotes lower grasp score
