### ISSUE TITLE
关于graspnetAPI中定义的夹爪坐标系的一些疑问

### ISSUE THREAD

**Issue by xiaomi2077** [graspnet/graspnet-baseline#62]
你好，关于在graspnetAPI中定义的夹爪坐标系，我有一些不太懂的地方。
![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/bab4a314-31e3-4da8-9e7e-da2f15a987ed)
Width:夹爪张开的宽度。
Height:夹爪的厚度 （[这里](https://github.com/graspnet/graspnet-baseline/issues/34#issuecomment-963129629)回答过）
0、Center是夹爪坐标系的原点吗
1、Center是在夹爪的什么位置？和论文里定义的一样，在夹爪的底部中点吗？
![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/e0a5a30b-f00d-485f-bbff-b62f1e6358a0)
2、Open Point是什么意思？
3、Depth是什么意思？是论文里夹爪坐标原点到物体表面最近的距离吗？还是接近向量与物体点云相交的点到夹爪坐标原点的距离？
![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/0215e14d-0c17-4170-af88-a0c1e2476f80)
4、这里的2cm是什么意思？

**Comment by chenxi-wang** [comment]
0/1/3. center是指物体上采样得到的一个点，以该点为基础生成grasp，它是夹爪坐标系的原点，距离夹爪最前端中心位置的距离为depth，实际抓取中建议加个offset，按夹爪最前端中心点对齐预测的pose和发送的指令
2. 这个是对应2d抓取的bounding box，左右边框的open point距离就是抓取宽度
4. 夹爪的底座部分到center的距离，这个2cm是为了计算碰撞用的，你可以根据自己需要改动
