### ISSUE TITLE
算法预测出的抓取宽度如何应用到实体机器人中？

### ISSUE THREAD

**Issue by xiaomi2077** [graspnet/graspnet-baseline#63]
算法预测的抓取宽度值比较大，不能作为最终的抓取宽度值。
![截屏-20230616152221-695x476](https://github.com/graspnet/graspnet-baseline/assets/33375652/34c06243-6365-49cd-8e84-1693768353cb)
![截屏-20230616152135-888x750](https://github.com/graspnet/graspnet-baseline/assets/33375652/daabde70-a876-495a-95f9-f87919ede6e9)
假如算法预测出的宽度是50mm，在实体机器人上部署算法时，是把50mm作为抓取动作执行时，夹爪的开始宽度吗？然后关闭夹爪直到robotiq85因为被抓取物体的阻挡而停止关闭动作。

**Comment by Fang-Haoshu** [comment]
是的

**Comment by WentangChen** [comment]
> 算法预测的抓取宽度值比较大，不能作为最终的抓取宽度值。 ![截屏-20230616152221-695x476](https://user-images.githubusercontent.com/33375652/246369189-34c06243-6365-49cd-8e84-1693768353cb.png) ![截屏-20230616152135-888x750](https://user-images.githubusercontent.com/33375652/246369205-daabde70-a876-495a-95f9-f87919ede6e9.png) 假如算法预测出的宽度是50mm，在实体机器人上部署算法时，是把50mm作为抓取动作执行时，夹爪的开始宽度吗？然后关闭夹爪直到robotiq85因为被抓取物体的阻挡而停止关闭动作。

你好！我也想将这个算法部署到机械臂上。请问一下你是修改demo.py这个文件来部署的吗？

**Comment by Fang-Haoshu** [comment]
部署的话根据demo里预测的grasp pose，让机器人运动到该位置即可

**Comment by WentangChen** [comment]
> 部署的话根据demo里预测的grasp pose，让机器人运动到该位置即可

十分感谢你的回复！请问一下你是用realsense相机获取rgb和depth数据的吗？
