### ISSUE TITLE
demo invisible

### ISSUE THREAD

**Issue by gothicwhw** [graspnet/graspnet-baseline#66]
I can't see anything in this open3d screen,Could you please provide any viable solutions?

WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
-> loaded checkpoint /home/hanwen.wang/code1/graspnet-baseline/check_point/checkpoint-kn.tar (epoch: 18)
![06a4d370488cbdb2c315b4a0701c9c7](https://github.com/graspnet/graspnet-baseline/assets/118330704/0b555f8b-07b8-4666-a2cc-a3f1f5335ea7)

**Comment by Fang-Haoshu** [comment]
Hi, it seems to be a windows version. We only tested the code under linux system. Perhaps you can try again with linux
