### ISSUE TITLE
This result is fantastic!

### ISSUE THREAD

**Issue by YKJK** [graspnet/graspnet-baseline#69]
1.Can you give me some advice on how to modify this model for real-time display of grasp poses?

2.Will my 3D camera, which produces black and white point clouds, affect the results I see?

3.I am currently unable to successfully generate the file format (like checkpoint-kn.tar).

4.I have previously filled out the form for AnyGrasp, and I currently need the file (.zip) urgently.
   license/
       |-- licenseCfg.json
       |-- [your_name].public_key
       |-- [your_name].signature
       |-- [your_name].lic

If you have seen this, please reply as soon as possible.

**Comment by chenxi-wang** [comment]
1. You can refer to open3d official documents and their visualization demo.
2. No. This model only needs point clouds as input.
3. This can be done with pytorch function.
4. Please provide your email filled in the form and I will have a check.

**Comment by YKJK** [comment]
Thank you for your response. I will try again!!
I will ask you if I have any questions.
I have just re-submitted the form. Please take a look again.

**Comment by chenxi-wang** [comment]
Your license has been sent a week ago. Did you check your mail box?
