### ISSUE TITLE
What means by grasp_height and grasp_depth?

### ISSUE THREAD

**Issue by gzchenjiajun** [graspnet/graspnet-baseline#7]
What means by grasp_height and grasp_width?

I read the source code models/graspnet.py:79,butI don't understand what grasp_height and grasp_depth mean.

I understand other parameters. For example, grasp_width is the gripper's gripping width.

thanks

**Comment by chenxi-wang** [comment]
Hi, you can find the definition in the figure at [Grasp Label Format](https://graspnetapi.readthedocs.io/en/latest/grasp_format.html#raw-label-format).

**Comment by gzchenjiajun** [comment]
![image](https://user-images.githubusercontent.com/13104274/104671031-f028c480-5717-11eb-9b7c-c59ea625d5d7.png)
Is it width, height, depth of the object?

**Comment by chenxi-wang** [comment]
No. They are all about grippers. The box stands for gripper coordinates.

**Comment by gzchenjiajun** [comment]
> No. They are all about grippers. The box stands for gripper coordinates.

I seem to understand.
These parameters score, width, height, depth, rotation_matrix, translation are all based on GRASP.
"Width" grasp width "height" depth "grasp height
But to some extent, width,height and depth are not used in my arm, I just need the posture (because my arm [XARM] is fixed, not adjustable in width,height and depth).
Do I understand you correctly?

**Comment by chenxi-wang** [comment]
Yes, you are right.

**Comment by gzchenjiajun** [comment]
> Yes, you are right.

'Points' records the grasp center point Coordinates in model frame.

I have read the understanding of Points, and I feel that if I want to make the manipulator run, I still need a center of mass coordinate of the object, right? (This parameter is not provided in the source code.)
I have to get it myself. Do I understand that right?

**Comment by gzchenjiajun** [comment]
> > Yes, you are right.
> 
> 'Points' records the grasp center point Coordinates in model frame.
> 
> I have read the understanding of Points, and I feel that if I want to make the manipulator run, I still need a center of mass coordinate of the object, right? (This parameter is not provided in the source code.)
> I have to get it myself. Do I understand that right?

Because the current network output values are all based on GRASP Angle data, but lack the information of objects (especially the center of mass of objects)

**Comment by chenxi-wang** [comment]
I can't get your idea. Grasp poses depend on local geometry features, and center of mass cannot be obtained from visual input. It is a model-free algorithm, with no specified objects.

**Comment by gzchenjiajun** [comment]
> I can't get your idea. Grasp poses depend on local geometry features, and center of mass cannot be obtained from visual input. It is a model-free algorithm, with no specified objects.

I would like to ask, what coordinate system is the output value of grasp translation (XYZ) based on? (I guess based on the center of the image (depth/color)?)

I thought it was based on the center of mass, could I be wrong?

**Comment by Fang-Haoshu** [comment]
based on camera coordinate.
Please refer to our paper

**Comment by gzchenjiajun** [comment]
Thank you very much for replying to me tonight!
Sorry, I will continue to refer to your article.

As a newcomer to this direction, I am not familiar with a lot of knowledge
