### ISSUE TITLE
A question about function `create_point_cloud_from_depth_image`

### ISSUE THREAD

**Issue by elenacliu** [graspnet/graspnet-baseline#71]
https://github.com/graspnet/graspnet-baseline/blob/46f649002bb8c7bb89bf0dfc1391aad3a919a1ea/utils/data_utils.py#L33-L43

In L38~L39, to get points' x, y coordinates in the camera space, why do you multiply `points_z`?

**Comment by chenxi-wang** [comment]
This is a basic transformation in point cloud computation. You can refer to related materials.
