### ISSUE TITLE
Question about grasping single thin object

### ISSUE THREAD

**Issue by baoyufuyou** [graspnet/graspnet-baseline#74]
Hi guys,
I found that when planning grasping for single thin object, there is always no candidates. Could I ask, it that normal? Thanks in advance.

**Comment by chenxi-wang** [comment]
How thin is the object? Did you visualize and check the input point cloud?

**Comment by baoyufuyou** [comment]
<img width="283" alt="Screenshot 2023-09-05 at 09 21 12" src="https://github.com/graspnet/graspnet-baseline/assets/39621208/1b720644-e618-402c-a308-df0a14b7a430">
The thin object is the HDMI cable with height about 1cm. I already checked the point cloud. When there are lots of cables in the scene, grasp planning could be done successfully. But when the cables are placed flat on the table, there are totally no candidates.

**Comment by chenxi-wang** [comment]
You mean multiple cables are placed flat but there are no candidates?

**Comment by baoyufuyou** [comment]
@chenxi-wang  Yes. For the scene with multiple cables or single cable placed flat on table, there is both no candidate.

**Comment by chenxi-wang** [comment]
That's weird. The most likely explanation is that cables are treated as part of the table. But I'm not sure. Perhaps you can try anygrasp sdk.
Btw, the machine feature id you provided seems incorrect. I've sent you an email several days ago.

**Comment by baoyufuyou** [comment]
@chenxi-wang Thanks a lot! I will try to submit the machine feature and try anygrasp sdk. Close this ticket and I will update the status later afterwards.
