### ISSUE TITLE
reported AP between paper and repo

### ISSUE THREAD

**Issue by xins981** [graspnet/graspnet-baseline#78]
The reported AP in this repo greater than paper. Is the contribuation of [collision detection in graspnetAPI](https://github.com/graspnet/graspnetAPI/blob/02dbe2d4093b90245905b758a1f25b49456c6c5a/graspnetAPI/utils/eval_utils.py#L357)?

To be fair, which report should compared with default test.py run using latest graspAPI lib?

**Comment by chenxi-wang** [comment]
For pair comparison, if you use collision detection in your method, you can compare it with the one in this repo. If not, just use the one in paper.
