### ISSUE TITLE
Segmentation Fault with GPU and not support CPU mode

### ISSUE THREAD

**Issue by pingguomaggie** [graspnet/graspnet-baseline#8]
Hi, thanks for sharing the code and it looks very interesting. I am try to run the code following the readme. But when I use GPU mode it runs into segmentation fault "net.to(device)". I tested both train.py and test.py and both have the same error. When I force device="CPU", it also fails. Do you know how to fix this? The detailed errors are follows:

GPU mode:
![image](https://user-images.githubusercontent.com/34848624/104813698-ce2d6000-5845-11eb-902b-fc488cff98f1.png)
![image](https://user-images.githubusercontent.com/34848624/104813925-18631100-5847-11eb-9600-8bf8ed3fbeaf.png)

CPU mode:
![image](https://user-images.githubusercontent.com/34848624/104813887-de920a80-5846-11eb-988b-8c23c6c666f1.png)
![image](https://user-images.githubusercontent.com/34848624/104813689-c077da80-5845-11eb-803f-81997f0e4517.png)

My environment is:
     RTX2080 Ti+ Ubuntu 18.04 + python 3.6 + cuda 10.1 + pytorch 1.6 

Thanks so much for your help!

**Comment by chenxi-wang** [comment]
pointnet2 operators do not support CPU mode.
For GPU mode, could you provide more information during execution? For example, set CUDA_LAUNCHING_BLOCK=1 before running the program. You can also import and convert net without other code to see if this error is caused by model device conversion.

**Comment by pingguomaggie** [comment]
Hi chenxi, thanks so much for your quick reply. I fix this problem! The GPU segmentation fault is due to the wrong link of pointnet and knn with cuda. There was two versions of cuda in my machine. I uninstalled one of them. But do not know why the pointnet and knn linked to the removed cuda. The problem is fix now by using the correct cuda link. Thanks again for your help! We can close this issue now!
