### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [graspnet/graspnet-baseline#84]
During run common_demo.sh, there is ImportError:

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

It seems like about grasp_nms package. How to fix it?

**Comment by MoonBunnyZZZ** [comment]
> During run common_demo.sh, there is ImportError:
> 
> ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use 'numpy._import_array' to disable if you are certain you don't need it).
> 
> It seems like about grasp_nms package. How to fix it?

I  put 'numpy.import_array()' after cimporting numpy in grasp_nms.pyx.The error don't occur.But I don't kown whether this is the only right way.

**Comment by chenxi-wang** [comment]
Maybe it's due to numpy version?

**Comment by MoonBunnyZZZ** [comment]
> Maybe it's due to numpy version?

which version in your python env?In my env, it's 1.19.0.

**Comment by chenxi-wang** [comment]
I didn't remember the version. You can try upgrading numpy directly.

**Comment by MoonBunnyZZZ** [comment]
> I didn't remember the version. You can try upgrading numpy directly.

I install the newest version numpy first.But there is error about "no.float" which is deprecated in version 1.20 .So I try version 1.19.

**Comment by MoonBunnyZZZ** [comment]
By the way, what is the gray point in point cloud generated by running demo .py?What does it mean?

**Comment by chenxi-wang** [comment]
> By the way, what is the gray point in point cloud generated by running demo .py?What does it mean?

Could you provide more details about "gray point"?

**Comment by MoonBunnyZZZ** [comment]
> > By the way, what is the gray point in point cloud generated by running demo .py?What does it mean?
> 
> Could you provide more details about "gray point"?

sorry for the delay
the gray point is in the top-right corner
![Screenshot from 2023-12-20 09-51-17](https://github.com/graspnet/graspnet-baseline/assets/30332524/4bd401b4-45b2-45dc-9b88-258ad9546d40)

**Comment by chenxi-wang** [comment]
Could it be the origin of the camera coordinates?

**Comment by captain316** [comment]
> > During run common_demo.sh, there is ImportError:
> > ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use 'numpy._import_array' to disable if you are certain you don't need it).
> > It seems like about grasp_nms package. How to fix it?
> 
> I put 'numpy.import_array()' after cimporting numpy in grasp_nms.pyx.The error don't occur.But I don't kown whether this is the only right way.

but,  where is grasp_nms.pyx? I can't find it.

**Comment by 15138676358** [comment]
The function "nms" is aimed at non-maximum suppression. I commented out the line 108 [e.g. gg.nms()] of the demo.py file directly, which seems to have no great effect on the results of the example.

**Comment by briller-zzj** [comment]
> > During run common_demo.sh, there is ImportError:
> > ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use 'numpy._import_array' to disable if you are certain you don't need it).
> > It seems like about grasp_nms package. How to fix it?
> 
> I put 'numpy.import_array()' after cimporting numpy in grasp_nms.pyx.The error don't occur.But I don't kown whether this is the only right way.

I'm also getting this error, but I can't find where the “grasp_nms.sh” file is, how did you fix it, could you tell me please?
