### ISSUE TITLE
文件读取时间过长问题

### ISSUE THREAD

**Issue by quanfeifan** [graspnet/graspnet-baseline#86]
你好，我在做抓取边框检测。我在训练时候发现GPU大多时候功率较低，代码大多数时间都在读取rgb和depth图片。请问有什么办法可以加速这个读取图片的速度吗？
比较夸张的对比：读取数据集时候要等好几分钟，然后GPU1秒1个batch

**Comment by chenxi-wang** [comment]
你是说每一次迭代的时候读取数据要几分钟吗，确实有点夸张了

**Comment by Cwyxx** [comment]
源代码是不是将所有训练数据加载到内存中，还没加载完，内存直接爆了
