### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by qwertyshen1001** [graspnet/graspnet-baseline#87]
![IMG_20240103_153541](https://github.com/graspnet/graspnet-baseline/assets/153064272/3393e29a-5dcd-4268-bf92-284dd4e4b76e)
![IMG_20240103_154726](https://github.com/graspnet/graspnet-baseline/assets/153064272/25096bc7-d4c4-41ff-a024-628f500d0da2)
运行demo.py是显示的图像出现问题，请问和realsense的分辨率有关系吗，还是应该调整depth图像的格式？

**Comment by chenxi-wang** [comment]
点云的单位不对，看看depth图合成点云前有没有转换成米
