### ISSUE TITLE
The process has been kill

### ISSUE THREAD

**Issue by taylorlulu** [graspnet/graspnet-baseline#89]
I encountered this problem when I'm running the command `CUDA_VISIBLE_DEVICES=0 python train.py --camera realsense --log_dir logs/log_rs --batch_size 1 --dataset_root dataset/data/graspnet`.
Which says:
```
Loading grasping labels...: 100%|███████████████| 88/88 [00:28<00:00,  3.07it/s]
Loading data path and collision labels...:  91%|▉| 91/100 [00:17<00:02,  3.32it/
Killed
```
Which might be caused by the full use of the memory of swap.
![swap](https://github.com/graspnet/graspnet-baseline/assets/49311079/3f185308-3c81-4ad0-ae6d-b6fa991f66bf)
How can I solved this problem? I would appreciate a lot for any help!

**Comment by chenxi-wang** [comment]
That's caused by OOM. You could train the model on a subset or upgrade your machine.
