### ISSUE TITLE
自定义workspace_mask

### ISSUE THREAD

**Issue by du-xinyi** [graspnet/graspnet-baseline#91]
如何自定义workspace_mask，我使用自定义的二值图取代workspace_mask后，会出现
```
    cloud_sampled = cloud_masked[idxs]
numpy.core._exceptions.MemoryError: Unable to allocate 732. GiB for an array with shape (20000, 1280, 1280, 3) and data type float64
```

**Comment by du-xinyi** [comment]
![mask](https://github.com/graspnet/graspnet-baseline/assets/73220784/bb8e9aed-27ba-4ef6-99ee-3b7b2dca4d7f)

**Comment by du-xinyi** [comment]
> ![mask](https://private-user-images.githubusercontent.com/73220784/296750276-bb8e9aed-27ba-4ef6-99ee-3b7b2dca4d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjA2NDcsIm5iZiI6MTcwNTMyMDM0NywicGF0aCI6Ii83MzIyMDc4NC8yOTY3NTAyNzYtYmI4ZTlhZWQtMjdiYS00ZWY2LTk5ZWUtM2I3YjJkY2E0ZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEyMDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDNlM2E0YWM0Y2U1OTdiZDA0NDgyMTY1NjUyN2MwOWRmZWNmZDJlZGUxMWNiODk2OWRjYmRiODY1OTZkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpUP5o373sQQqbxMnPrxf0I3DsdDUEy_ruzmJGWtfsQ)

这是我设置的掩膜

**Comment by xinchaosong** [comment]
Is your `workspace_mask` a boolean matrix? It must be a boolean matrix, not a numeric matrix.

**Comment by chenxi-wang** [comment]
在mask过后，点云大小应该是N x 3，根据提示的信息，你在masking这步出了问题，可以检查一下mask是不是布尔值
