### ISSUE TITLE
How to generate scene collision labels for custom datasets?

### ISSUE THREAD

**Issue by xinchaosong** [graspnet/graspnet-baseline#96]
Thank you very much for sharing your annotation toolbox with me last week. I'm wondering if there are also tools available that I can use to generate the collision labels for each scene in my own dataset. I'm currently trying to adapt the code in your toolbox to do this, but I'm not sure if this is the best way to go. The scenes in my dataset are very simple: I have only one object in each scene and I just need to detect if any grasps in the generated grasp labels collide with the tabletop. Thank you in advance for any advice.

**Comment by chenxi-wang** [comment]
Hi, you're right. The easiest way is to adapt the code in graspnetAPI or utils/collision_detector.py to your project. We use a similar function in GraspNet annotation.
