### ISSUE TITLE
Increasing GPU memory during training time: Cuda out for memory error

### ISSUE THREAD

**Issue by lishiyu005** [graspnet/graspnet-baseline#97]
Dear authors,

Thanks for your great work. When I try to train the models, the GPU memory increase from 10 GB in the beginning to more than 20GB after 300 batches. How did you solve the problems? Is there any way to fix this issue?

Best regards,
Shiyu Li

**Comment by chenxi-wang** [comment]
Hi, if you met cuda OOM, you can try sampling the points or reducing the training data.
