### ISSUE TITLE
test.py AP比论文中的高不少

### ISSUE THREAD

**Issue by qwertyshen1001** [graspnet/graspnet-baseline#99]
你好作者，请问使用开源的graspness代码时，运行test.py的时候--collision_thresh -1 是使用了碰撞检测还是没有碰撞检测CD。我按照您开源的代码运行了10个epoach，得到的AP Seen=0 ，690087 4468655022，AP Similar=0 .6030403 100697231，AP Novel=0. 25724010891913146，每一个值都比论文中的高不少，AP Similar甚至提高了5，请问是哪里的问题。

**Comment by chenxi-wang** [comment]
你好，这是有可能的，这份代码是第三方复现的结果，不是我们原版的实现，效果可能有差异

**Comment by Fang-Haoshu** [comment]
@qwertyshen1001 对的，我们后来改了一下collision，repo里的results部分已经列出来现在的结果了，参见https://github.com/graspnet/graspnet-baseline?tab=readme-ov-file#results

@chenxi-wang 这是baseline哈哈，我们自己的implement，不是那个graspness的
